# Generated by Django 3.2.2 on 2023-06-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='BVr=zjJ.9SQm#(|YC$1(@e\\"fj0Hsig?o34H6?Oo,gyi57Ehjr~cYyc[T}u8,T=np=FGwtm?8[Hep_3M}lbUn(IwMut[', max_length=100),
        ),
    ]
