# Generated by Django 3.2.2 on 2023-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='O=ZYN.a+yV=tfr8gG8U59C&1vf7W/.acqX;a?kfcaF', max_length=100),
        ),
    ]
