# Generated by Django 3.2.2 on 2023-06-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default="R-K}Y,KQ%JN,7GiwLLeo.;2qE`A<<RXWc;hLP*mE3d7'on+_\\'VRjN5Vf#6lO=p$Gi;h!FCFX-}", max_length=100),
        ),
    ]
