# Generated by Django 3.2.2 on 2023-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='N)dL`XF7t[v@', max_length=100),
        ),
    ]
