# Generated by Django 3.2.2 on 2023-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='N!p`J%sOQ2pW$\\^p:', max_length=100),
        ),
    ]
