# Generated by Django 3.2.2 on 2023-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='E"*[IV%79Ps=(2j3|Mj', max_length=100),
        ),
    ]
