# Generated by Django 3.2.2 on 2023-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='Rau6?N08', max_length=100),
        ),
    ]
