# Generated by Django 3.2.2 on 2023-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='|ZLd|u|M:RL', max_length=100),
        ),
    ]
