# Generated by Django 3.2.2 on 2023-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='NO@o{tu}CvYM5i-O5^+', max_length=100),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.CharField(max_length=800, unique=True),
        ),
    ]
