# Generated by Django 3.2.2 on 2023-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_auto_20230612_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='|n|u#WL=xQ', max_length=100),
        ),
    ]
