# Generated by Django 3.2.2 on 2023-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_alter_password_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='QtXpKD/F?', max_length=100),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.CharField(max_length=800),
        ),
        migrations.AddConstraint(
            model_name='password',
            constraint=models.UniqueConstraint(fields=('url', 'user_id'), name='unique_url_and_user_id'),
        ),
    ]
