# Generated by Django 3.2.2 on 2023-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_auto_20230612_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='e0"pv=[o-A-Q0', max_length=100),
        ),
    ]
