# Generated by Django 3.2.2 on 2023-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0021_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='%1!y^HHY:o_]66>v@', max_length=100),
        ),
    ]
