# Generated by Django 3.2.2 on 2023-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0022_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='K7o1/HS#BP-^-M{', max_length=100),
        ),
    ]
