# Generated by Django 3.2.2 on 2023-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0023_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default=";<ip4n2Zf@Z(:+*6Y'c", max_length=100),
        ),
    ]
