# Generated by Django 3.2.2 on 2023-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='x{?3x3))C', max_length=100),
        ),
    ]
