# Generated by Django 3.2.2 on 2023-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0025_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default=']$3l7{}pBO|2Q', max_length=100),
        ),
    ]
