# Generated by Django 3.2.2 on 2023-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0026_alter_password_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='password',
            name='unique_url_and_user_id',
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='~4?b\'"R9}^w>t]wM6', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='password',
            constraint=models.UniqueConstraint(fields=('url', 'user'), name='unique_url_and_user_id'),
        ),
    ]
