# Generated by Django 3.2.2 on 2023-06-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0027_auto_20230612_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='}pn>}PxAjkc=h"22.sv', max_length=100),
        ),
    ]
